services:
  worker:
    image: printguardian
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    volumes:
      - ./input_file.jpg:/usr/src/app/input_file.jpg
