services:
  worker:
    image: printguardian
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    volumes:
      - ./model:/usr/src/app/model
    healthcheck:
      test: ["CMD-SHELL", "test -f .ready || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    devices:
      # VAAPI Devices
      - /dev/dri:/dev/dri
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1024M
        reservations:
          cpus: '4'
          memory: 512M
