services:
  worker:
    image: printguardian
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    volumes:
      - ./input_file.jpg:/usr/src/app/input_file.jpg
      - ./model-weights.darknet:/usr/src/app/model-weights.darknet:ro
    healthcheck:
      test: ["CMD-SHELL", "test -f .ready || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s